permalink: pretty
exclude: [
  "CNAME", "README.md", "package.json", "node_modules",
  "bower_components/select2/docs"
]

base_path: "travels.oxy.fi"
permalink: /:categories/:title/

title: "Travel log of Oskar Schöldström"
description: A Personal travel log of Oskar Schöldström

author:
  name: Oskar Schöldström
  email: public@oxy.fi
  googleplus: https://plus.google.com/114201888556629445485
  twitter: scholdstrom
  github: oxyc
  picasa: 114201888556629445485
  instagram: "@oskar.scholdstrom"

google_analytics: UA-6980403-12

# https://picasaweb.google.com/data/feed/base/user/114201888556629445485/albumid/
