permalink: pretty
exclude: [
  "CNAME", "README.md", "package.json", "node_modules", "bower_components"
]

base_path: "travels.oxy.fi"
permalink: /:categories/:title/

title: "Travel log of Oskar Schöldström"
description: A collection of places I've seen, routes I've traveled and how much I spent while doing it

author:
  name: Oskar Schöldström
  email: public@oxy.fi
  googleplus: https://plus.google.com/114201888556629445485
  twitter: scholdstrom
  github: oxyc
  picasa: 114201888556629445485
  instagram: "@oskar.scholdstrom"

google_analytics: UA-6980403-12

gems:
  - jekyll-feed

# https://picasaweb.google.com/data/feed/base/user/114201888556629445485/albumid/
