base_path: travels.oxy.fi
permalink: '/:categories/:title/'
title: Travel log of Oskar Schöldström
description: >-
  A collection of places I've seen, routes I've traveled and how much I spent
  while doing it
assets:
  /scripts/app.js: /scripts/app.js?id=ebc38957406d656d176e
  /styles/app.css: /styles/app.css?id=53a99007fbd0cec040fb
  /../_includes/abovefold.css: /../_includes/abovefold.css?id=18fc17da1e09e9f171ac
  /scripts/manifest.js: /scripts/manifest.js?id=3c768977c2574a34506e
  /scripts/vendor.js: /scripts/vendor.js?id=73399bfb3e92a5ad5380
author:
  name: Oskar Schöldström
  email: public@oxy.fi
  googleplus: 'https://plus.google.com/114201888556629445485'
  twitter: scholdstrom
  github: oxyc
  picasa: 114201888556629440000
  instagram: '@oskar.scholdstrom'
google_analytics: UA-6980403-12
disqus: //travelsoxyfi.disqus.com
plugins:
  - jekyll-feed
exclude:
  - CNAME
  - README.md
  - package.json
  - vendor
  - bower_components
  - node_modules
