base_path: travels.oxy.fi
permalink: '/:categories/:title/'
title: Travel log of Oskar Schöldström
description: >-
  A collection of places I've seen, routes I've traveled and how much I spent
  while doing it
assets:
  /scripts/app.js: /scripts/app.js?id=011b6ae63977694b1ecf
  /styles/app.css: /styles/app.css?id=5c11b71c271e17d8a809
  /../_includes/abovefold.css: /../_includes/abovefold.css?id=c9dc36029dfa6a083d85
  /scripts/app.js.map: /scripts/app.js.map?id=9e90a7597dc84200c3c4
  /styles/app.css.map: /styles/app.css.map?id=7b927298d8cbdcab4177
  /../_includes/abovefold.css.map: /../_includes/abovefold.css.map?id=0c9cf2932d2d5726a728
  /scripts/manifest.js: /scripts/manifest.js?id=3c768977c2574a34506e
  /scripts/manifest.js.map: /scripts/manifest.js.map?id=b2ab14a71f9ded54320b
  /scripts/vendor.js: /scripts/vendor.js?id=2dbb956815758e1ae22f
  /scripts/vendor.js.map: /scripts/vendor.js.map?id=568895ab5ebbc68c4cc7
author:
  name: Oskar Schöldström
  email: public@oxy.fi
  googleplus: 'https://plus.google.com/114201888556629445485'
  twitter: scholdstrom
  github: oxyc
  picasa: 114201888556629440000
  instagram: '@oskar.scholdstrom'
google_analytics: UA-6980403-12
disqus: //travelsoxyfi.disqus.com
plugins:
  - jekyll-feed
exclude:
  - CNAME
  - README.md
  - package.json
  - vendor
  - bower_components
  - node_modules
